-- AI_GENERATE_START -
CREATE TABLE IF NOT EXISTS backtest_run (
    id BIGINT NOT NULL AUTO_INCREMENT,
    result_id VARCHAR(64) NOT NULL,
    baseline_type VARCHAR(32) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(24) NOT NULL,
    degraded BOOLEAN NOT NULL DEFAULT TRUE,
    data_version VARCHAR(255) NOT NULL,
    stock_pool_version VARCHAR(255) NOT NULL,
    feature_version VARCHAR(128) NOT NULL,
    fee_version VARCHAR(128) NOT NULL,
    code_version VARCHAR(128) NOT NULL,
    total_return DECIMAL(20, 10) NOT NULL,
    annualized_return DECIMAL(20, 10) NOT NULL,
    max_drawdown DECIMAL(20, 10) NOT NULL,
    net_return_1000 DECIMAL(20, 10) NOT NULL,
    net_return_5000 DECIMAL(20, 10) NOT NULL,
    net_return_10000 DECIMAL(20, 10) NOT NULL,
    total_trades INT NOT NULL,
    win_trades INT NOT NULL,
    win_rate DECIMAL(20, 10) NOT NULL,
    avg_profit DECIMAL(20, 10) NOT NULL,
    avg_loss DECIMAL(20, 10) NOT NULL,
    blocked_trades INT NOT NULL,
    skipped_trades INT NOT NULL,
    cost_time_ms BIGINT NOT NULL,
    request_json JSON NOT NULL,
    limitations_json JSON NOT NULL,
    calculated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_backtest_run_result_id (result_id),
    KEY idx_backtest_run_range_type (start_date, end_date, baseline_type),
    KEY idx_backtest_run_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS backtest_trade (
    id BIGINT NOT NULL AUTO_INCREMENT,
    result_id VARCHAR(64) NOT NULL,
    sequence_no INT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    signal_date DATE NOT NULL,
    entry_date DATE NOT NULL,
    planned_exit_date DATE NOT NULL,
    actual_exit_date DATE NULL,
    raw_entry_price DECIMAL(18, 4) NULL,
    raw_exit_price DECIMAL(18, 4) NULL,
    executed_entry_price DECIMAL(18, 4) NULL,
    executed_exit_price DECIMAL(18, 4) NULL,
    quantity INT NOT NULL DEFAULT 0,
    quantity_1000 INT NOT NULL DEFAULT 0,
    quantity_10000 INT NOT NULL DEFAULT 0,
    gross_return DECIMAL(20, 10) NOT NULL,
    total_fee DECIMAL(18, 4) NOT NULL,
    net_profit DECIMAL(20, 4) NOT NULL,
    net_profit_1000 DECIMAL(20, 4) NOT NULL,
    net_profit_10000 DECIMAL(20, 4) NOT NULL,
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_backtest_trade_sequence (result_id, sequence_no),
    KEY idx_backtest_trade_stock_date (stock_code, entry_date),
    KEY idx_backtest_trade_result_status (result_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- AI_GENERATE_END -
