# 声明StatefulSet
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  name: found-front
  labels:
    app: found-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: found-front
  # serviceName: found-front
  template:
    metadata:
      labels:
        app: found-front
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/mwangli/found-front
        imagePullPolicy: Always
        name: found-front
        readinessProbe:
           # initialDelaySeconds: 10
           # periodSeconds: 3
          httpGet:
            port: 80
            path: /
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
        # 挂载配置到configMap
        - name: nginx-config
          configMap:
            name: nginx-conf
            items:
            - key: nginx.conf
              path: nginx.conf
---
# 声明ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
#  namespace: dafault
data:
  nginx.conf: |
   server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }
     location /api  {
        proxy_pass http://found-trading-svc:8080/;
    }
   }
---
# 声明Service服务
apiVersion: v1
kind: Service
metadata:
  name: found-front-svc
  labels:
    app: found-front
spec:
  type: NodePort
  selector:
    app: found-front
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 80
---
# 镜像仓库密钥
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1zaGVuemhlbi5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJsaW1pbmd3YW5nMDYiLCJwYXNzd29yZCI6IkRrbmhmcmUxc3QiLCJhdXRoIjoiYkdsdGFXNW5kMkZ1WnpBMk9rUnJibWhtY21VeGMzUT0ifX19
metadata:
  name: registry-secret
