# 声明StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-server
  labels:
    app: mongo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-server
  serviceName: mongo-server
  template:
    metadata:
      labels:
        app: mongo-server
    spec:
      containers:
        - name: mongodb-server
          image: mongo
          ports:
            - containerPort: 27017 # MongoDB 默认端口号。
          volumeMounts:
            - name: mongo-data # 持久化存储卷名称。
              mountPath: /data/db # mongo默认存储路径
          #envFrom:
          #  - secretRef:
          #      name: mongo-secret # 引用上述创建的 Secret。
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: '****.******'
          resources:
            limits:
              memory: "1024Mi"
              #cpu: "500m"
            requests:
              memory: "64Mi"
              #cpu: "100m"
      volumes:
        # 挂载数据到PVC
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data-pvc-8g
        # 挂载配置到configMap
---
# 声明PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc-8g
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
---
# 声明PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv-8g
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    # 需要提前创建好文件夹
    path: /local/data/mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - test
---
# 声明mongo服务
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongo-svc
spec:
  type: NodePort
  selector:
    app: mongo-server
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 27017
# 创建mongo用户名密码
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mogno-secret
data:
  password: Um9vdC4xMjM0NTY=
  username: cm9vdA==


