# 声明StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  serviceName: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-cn
        resources:
          #limits:
          #  cpu: 100m
          #  memory: 2000Mi
          requests:
          #  cpu: 100m
            memory: 200Mi
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: MYSQL_ROOT_PASSWORD
          value: '****.******'
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        - mountPath: /etc/mysql/conf.d
          name: mysql-config
      volumes:
        # 挂载数据到PVC
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc-1g
        # 挂载配置到configMap
        - name: mysql-config
          configMap:
            name: my.cnf
            items:
            - key: my.cnf
              path: my.cnf
---
# 声明PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc-1g
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
# 声明PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv-1g
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    # 需要提前创建好文件夹
    path: /local/data/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - test
---
# 声明ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: my.cnf
#  namespace: dafault
data:
  my.cnf: |
    # mysql config
    [mysqld]
    max_connect_errors=1000
    default_authentication_plugin=mysql_native_password
    # 启用慢查询日志
    slow_query_log=1 
    # 将慢查询时间设置为2秒
    long_query_time=2
    # skip-grant-tables
---
# 声明Service服务
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-svc
spec:
  type: NodePort
  selector:
    app: mysql-server
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 3306
