# 声明StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  serviceName: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - image: redis
        name: redis-server
        env: 
          - name: TZ
            value: Asia/Shanghai
        command:
          - redis-server
          - "/etc/redis/redis.conf"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        - mountPath: /etc/redis
          name: redis-config
      volumes:
        # 挂载数据到PVC
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pvc-100m
        # 挂载配置到configMap
        - name: redis-config
          configMap:
            name: redis-conf
            items:
            - key: redis.conf
              path: redis.conf
---
# 声明PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc-100m
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
---
# 声明PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv-100m
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  local:
    # 需要提前创建好文件夹
    path: /local/data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - test
---
# 声明ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
#  namespace: dafault
data:
  redis.conf: |
    appendonly yes
    requirepass ****.******
---
# 声明redis服务
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis-svc
spec:
  type: NodePort
  selector:
    app: redis-server
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 6379
