# 声明StatefulSet
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  name: stock-trading
  labels:
    app: stock-trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-trading
 # serviceName: stock-trading
  template:
    metadata:
      labels:
        app: stock-trading
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/mwangli/stock-trading
        imagePullPolicy: Always
        name: stock-trading
        resources:        
          limits:
            memory: "2048Mi"
            cpu: "1800m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            port: 8080
            path: /test/alive
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            port: 8080
            path: /test/alive
        env:
        - name: PROFILE
          value: prod
        - name: TZ
          value: Asia/Shanghai
        - name: MONGO_HOST
          value: mongo-svc
        - name: MONGO_PASS
          value: '****.******'
        - name: REDIS_HOST
          value: redis-svc
        - name: REDIS_PASS
          value: '****.******'
        - name: MYSQL_HOST
          value: mysql-svc
        - name: MYSQL_PASS
          value: '****.******'
        ports:
        - containerPort: 8080
---
# 声明Service服务
apiVersion: v1
kind: Service
metadata:
  name: stock-trading-svc
  labels:
    app: stock-trading
spec:
  type: NodePort
  selector:
    app: stock-trading
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 8080
---
# 镜像仓库密钥
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1zaGVuemhlbi5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJsaW1pbmd3YW5nMDYiLCJwYXNzd29yZCI6IkRrbmhmcmUxc3QiLCJhdXRoIjoiYkdsdGFXNW5kMkZ1WnpBMk9rUnJibWhtY21VeGMzUT0ifX19
metadata:
  name: registry-secret
