-- AI_GENERATE_START -
CREATE TABLE IF NOT EXISTS trade_command (
    id BIGINT NOT NULL AUTO_INCREMENT,
    command_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(64) NULL,
    account_id VARCHAR(64) NOT NULL,
    broker_code VARCHAR(32) NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    market VARCHAR(16) NULL,
    side VARCHAR(16) NOT NULL,
    order_type VARCHAR(16) NOT NULL DEFAULT 'LIMIT',
    requested_price DECIMAL(18, 4) NOT NULL,
    requested_quantity INT NOT NULL,
    estimated_amount DECIMAL(20, 4) NULL,
    trading_mode VARCHAR(24) NOT NULL,
    status VARCHAR(32) NOT NULL,
    trade_date DATE NOT NULL,
    valid_until DATETIME(3) NULL,
    authorization_id VARCHAR(64) NULL,
    model_version VARCHAR(128) NULL,
    feature_snapshot_id VARCHAR(64) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_command_command_id (command_id),
    UNIQUE KEY uk_trade_command_idempotency_key (idempotency_key),
    KEY idx_trade_command_date_status (trade_date, status),
    KEY idx_trade_command_stock_created (stock_code, created_at),
    CONSTRAINT chk_trade_command_quantity CHECK (requested_quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS account_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    snapshot_id VARCHAR(64) NOT NULL,
    broker_code VARCHAR(32) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    total_assets DECIMAL(20, 4) NULL,
    available_cash DECIMAL(20, 4) NULL,
    frozen_cash DECIMAL(20, 4) NULL,
    market_value DECIMAL(20, 4) NULL,
    daily_profit_loss DECIMAL(20, 4) NULL,
    captured_at DATETIME(3) NOT NULL,
    source VARCHAR(32) NOT NULL,
    raw_event_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_account_snapshot_id (snapshot_id),
    UNIQUE KEY uk_account_snapshot_capture (account_id, captured_at, source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS position_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    snapshot_id VARCHAR(64) NOT NULL,
    broker_code VARCHAR(32) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    captured_at DATETIME(3) NOT NULL,
    source VARCHAR(32) NOT NULL,
    raw_event_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_position_snapshot_id (snapshot_id),
    KEY idx_position_snapshot_account_capture (account_id, captured_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS position_snapshot_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    snapshot_id VARCHAR(64) NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    market VARCHAR(16) NULL,
    shareholder_account VARCHAR(64) NOT NULL DEFAULT '',
    total_quantity INT NOT NULL DEFAULT 0,
    available_quantity INT NOT NULL DEFAULT 0,
    frozen_quantity INT NOT NULL DEFAULT 0,
    average_cost DECIMAL(18, 4) NULL,
    current_price DECIMAL(18, 4) NULL,
    market_value DECIMAL(20, 4) NULL,
    first_buy_date DATE NULL,
    last_buy_date DATE NULL,
    captured_at DATETIME(3) NOT NULL,
    raw_event_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_position_snapshot_item (snapshot_id, stock_code, shareholder_account),
    KEY idx_position_snapshot_item_stock (stock_code, captured_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS risk_decision (
    id BIGINT NOT NULL AUTO_INCREMENT,
    decision_id VARCHAR(64) NOT NULL,
    command_id VARCHAR(64) NOT NULL,
    passed BOOLEAN NOT NULL,
    rule_version VARCHAR(64) NOT NULL,
    violations_json JSON NULL,
    account_snapshot_id VARCHAR(64) NULL,
    position_snapshot_id VARCHAR(64) NULL,
    evaluated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_risk_decision_id (decision_id),
    KEY idx_risk_decision_command_time (command_id, evaluated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS broker_order (
    id BIGINT NOT NULL AUTO_INCREMENT,
    command_id VARCHAR(64) NOT NULL,
    attempt_no INT NOT NULL,
    broker_code VARCHAR(32) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    broker_order_no VARCHAR(64) NULL,
    client_order_no VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL,
    raw_status VARCHAR(64) NULL,
    order_price DECIMAL(18, 4) NOT NULL,
    order_quantity INT NOT NULL,
    filled_quantity INT NOT NULL DEFAULT 0,
    average_fill_price DECIMAL(18, 4) NULL,
    submitted_at DATETIME(3) NULL,
    last_queried_at DATETIME(3) NULL,
    terminal_at DATETIME(3) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_broker_order_attempt (command_id, attempt_no),
    UNIQUE KEY uk_broker_order_broker_no (broker_code, account_id, broker_order_no),
    KEY idx_broker_order_status_query (status, last_queried_at),
    CONSTRAINT chk_broker_order_attempt CHECK (attempt_no > 0),
    CONSTRAINT chk_broker_order_quantity CHECK (order_quantity > 0),
    CONSTRAINT chk_broker_order_filled CHECK (filled_quantity >= 0 AND filled_quantity <= order_quantity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS broker_fill (
    id BIGINT NOT NULL AUTO_INCREMENT,
    broker_order_id BIGINT NULL,
    broker_code VARCHAR(32) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    broker_fill_no VARCHAR(64) NOT NULL,
    broker_order_no VARCHAR(64) NULL,
    synthetic_key BOOLEAN NOT NULL DEFAULT FALSE,
    stock_code VARCHAR(16) NOT NULL,
    side VARCHAR(16) NOT NULL,
    fill_price DECIMAL(18, 4) NOT NULL,
    fill_quantity INT NOT NULL,
    fill_amount DECIMAL(20, 4) NOT NULL,
    commission DECIMAL(18, 4) NULL,
    stamp_duty DECIMAL(18, 4) NULL,
    transfer_fee DECIMAL(18, 4) NULL,
    other_fee DECIMAL(18, 4) NULL,
    trade_date DATE NOT NULL,
    filled_at DATETIME(3) NOT NULL,
    raw_event_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_broker_fill_no (broker_code, account_id, broker_fill_no),
    KEY idx_broker_fill_order (broker_order_id),
    KEY idx_broker_fill_stock_date (stock_code, trade_date),
    CONSTRAINT chk_broker_fill_quantity CHECK (fill_quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS broker_sync_batch (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_id VARCHAR(64) NOT NULL,
    broker_code VARCHAR(32) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    sync_type VARCHAR(32) NOT NULL,
    window_start DATE NULL,
    window_end DATE NULL,
    cursor_value VARCHAR(128) NULL,
    status VARCHAR(32) NOT NULL,
    request_count INT NOT NULL DEFAULT 0,
    received_count INT NOT NULL DEFAULT 0,
    inserted_count INT NOT NULL DEFAULT 0,
    updated_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    last_error VARCHAR(500) NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_broker_sync_batch_id (batch_id),
    UNIQUE KEY uk_broker_sync_window (broker_code, account_id, sync_type, window_start, window_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS trade_authorization (
    id BIGINT NOT NULL AUTO_INCREMENT,
    authorization_id VARCHAR(64) NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    allowed_mode VARCHAR(24) NOT NULL,
    max_single_amount DECIMAL(20, 4) NOT NULL,
    max_daily_amount DECIMAL(20, 4) NOT NULL,
    max_daily_trade_count INT NOT NULL,
    effective_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    status VARCHAR(24) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    revoked_at DATETIME(3) NULL,
    revoke_reason VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_authorization_id (authorization_id),
    KEY idx_trade_authorization_account_status (account_id, status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS trade_event_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_id VARCHAR(64) NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME(3) NULL,
    last_error VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    sent_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_event_outbox_id (event_id),
    KEY idx_trade_event_outbox_delivery (status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS execution_audit (
    id BIGINT NOT NULL AUTO_INCREMENT,
    audit_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(64) NULL,
    account_id VARCHAR(64) NULL,
    command_id VARCHAR(64) NULL,
    broker_order_no VARCHAR(64) NULL,
    trading_mode VARCHAR(24) NULL,
    result VARCHAR(32) NOT NULL,
    detail_json JSON NULL,
    trace_id VARCHAR(64) NULL,
    occurred_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_execution_audit_id (audit_id),
    KEY idx_execution_audit_command_time (command_id, occurred_at),
    KEY idx_execution_audit_event_time (event_type, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- AI_GENERATE_END -
